# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  - group: Idd
  - name: System.Debug
    value: 'true'

resources:
  pipelines:
  - pipeline: DastAttackerCli  # Name of the pipeline resource
    source: dast-attacker-cli  # Name of the pipeline referenced by the pipeline resource
    trigger:
      branches:
      - test-trigger
      - master

jobs:
- job: Publish
  pool:
    vmImage: ubuntu-latest

  steps:
    - script: |
        echo "Group variable: idd_release = $(idd_release)"
        echo "Build.BuildId = $(Build.BuildId)"
        echo "Build.StagingDirectory = $(Build.StagingDirectory)"
        echo "Build.ArtifactStagingDirectory = $(Build.ArtifactStagingDirectory)"
        echo "Pipeline.Workspace = $(Pipeline.Workspace)"
      displayName: 'Echo Group variable and Build.BuildId'

    - download: DastAttackerCli
      artifact: linux
      patterns: "*.deb"
      displayName: 'Download dast-attacker-cli Debian Artifact'
    - bash: |
        GIT_TAG=${GIT_TAG:-$(idd_release).$(Build.BuildId)}
        echo "##vso[task.setvariable variable=GIT_TAG]$GIT_TAG"
        echo "Tag is ${GIT_TAG}"
      displayName: 'Generate Tag'
    - task: GitHubRelease@1
      displayName: 'Push to Distribution Release'
      inputs:
        gitHubConnection: github.com
        repositoryName: whitehatsec-innovations/distribution
        action: create
        target: $(Build.SourceVersion)
        tagSource: userSpecifiedTag
        tag: $(GIT_TAG)
        addChangeLog: false
        isPreRelease: true
        assetUploadMode: replace
        assets: |
          $(Pipeline.Workspace)/DastAttackerCli/linux/*
